// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8f7AVL46R2nC9KeL42EraU5MRKM6suo',
    appId: '1:664752376040:web:45ad6f45e26044ee76615d',
    messagingSenderId: '664752376040',
    projectId: 'west-segregation',
    authDomain: 'west-segregation.firebaseapp.com',
    storageBucket: 'west-segregation.firebasestorage.app',
    measurementId: 'G-NWME3P5MV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxdc1peABJydNJkpWs5N6mrKhQSfZr8iw',
    appId: '1:664752376040:android:4f1a074dce58d01076615d',
    messagingSenderId: '664752376040',
    projectId: 'west-segregation',
    storageBucket: 'west-segregation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37YDYeq7nx4j6Axj7wHRy8iJNLA3Adn4',
    appId: '1:664752376040:ios:f74239159adb329e76615d',
    messagingSenderId: '664752376040',
    projectId: 'west-segregation',
    storageBucket: 'west-segregation.firebasestorage.app',
    iosBundleId: 'com.example.westSegregation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37YDYeq7nx4j6Axj7wHRy8iJNLA3Adn4',
    appId: '1:664752376040:ios:f74239159adb329e76615d',
    messagingSenderId: '664752376040',
    projectId: 'west-segregation',
    storageBucket: 'west-segregation.firebasestorage.app',
    iosBundleId: 'com.example.westSegregation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm8f7AVL46R2nC9KeL42EraU5MRKM6suo',
    appId: '1:664752376040:web:fe85c20004f30c6e76615d',
    messagingSenderId: '664752376040',
    projectId: 'west-segregation',
    authDomain: 'west-segregation.firebaseapp.com',
    storageBucket: 'west-segregation.firebasestorage.app',
    measurementId: 'G-9W4K15CZZQ',
  );
}
